version: '3.7'
services:
  web-factory:
    container_name: ${PROJECT_NAME}_WEB
    image: nginx:latest
    restart: always
    volumes:
      #Set default configuration to nginx  
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
      # share projet folder with nginx
      - ./app/back:/var/www/pepite
    labels:
      # permet de créer un routeur Traefik 
      - "traefik.enable=true" 
      - "traefik.http.services.eshop.loadbalancer.server.port=80"
      - "traefik.http.routers.eshop.rule=Host(`websocket.objetrama.tech`)"
      - "traefik.http.routers.eshop.entrypoints=websecure"
      - "traefik.http.routers.eshop.tls.certresolver=myhttpchallenge"
    env_file:
      - .env
    networks:
      default:
        aliases:
          - factory.dev
  phpfactory:
    container_name: ${PROJECT_NAME}_PHP
    networks:
      project-network:
      external-network:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: '${USER_ID:-1000}'
        GROUP_ID: '${GROUP_ID:-1000}'
        USER: '${USER:-User}'

    volumes:
      - ./app/back:/var/www/pepite
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mysql
    labels:
      # permet de créer un routeur Traefik 
      - "traefik.enable=true"
      - "traefik.http.services.eshop.loadbalancer.server.port=3001"
      - "traefik.http.routers.eshop.rule=Host(`wss.objetrama.tech`)"
      - "traefik.http.routers.eshop.entrypoints=websecure"
      - "traefik.http.routers.eshop.tls.certresolver=myhttpchallenge"
  mysql:
    image: mariadb:latest
    container_name: ${PROJECT_NAME}_MYSQL
    command: --max_allowed_packet=130023424
    networks:
      - project-network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysqldataFactory:/var/lib/mysql
    env_file:
      - .env
networks:
  default:
    name: dev
  project-network:
    name: ${PROJECT_NAME}-NETOWRKs
    internal: true
  external-network:
    name: ${PROJECT_NAME}-EXTERNAL-NETOWRKs
    external: true
volumes:
  mysqldataFactory: {}
