version: '3.7'
services:
  web-factory:
    container_name: ${PROJECT_NAME}_WEB
    image: nginx:latest
    restart: always
    volumes:
      #Set default configuration to nginx  
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
      # share projet folder with nginx
      - ./app/back:/var/www/app
    labels:
      # permet de créer un routeur Traefik 
      - "traefik.http.services.poc_cqrs_web.loadbalancer.server.port=80"
      - "traefik.http.routers.poc_cqrs_web.rule=Host(`${DOMAINE}.traefik.me`)"
      - "traefik.http.routers.poc_cqrs_web-tls.tls.domains[0].main=${DOMAINE}.traefik.me"
      - "traefik.http.routers.poc_cqrs_web-tls.tls.domains[0].sans=${DOMAINE}-*.traefik.me"
      - "traefik.http.routers.poc_cqrs_web.tls=true"
    env_file:
      - .env
    networks:
      - default
      - project-network
  php:
    container_name: ${PROJECT_NAME}_PHP
    networks:
      - project-network
      - default
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: '${USER_ID:-1000}'
        GROUP_ID: '${GROUP_ID:-1000}'
        USER: '${USER:-User}'

    volumes:
      - ./app:/var/www/app
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mariadb:latest
    container_name: ${PROJECT_NAME}_MYSQL
    command: --max_allowed_packet=130023424
    networks:
      - project-network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysqldataFactory:/var/lib/mysql
    env_file:
      - .env
networks:
  default:
    name: dev
  project-network:
    name: ${PROJECT_NAME}-NETOWRKs
    internal: true
  external-network:
    name: ${PROJECT_NAME}-EXTERNAL-NETOWRKs
    external: true
volumes:
  mysqldataFactory: {}
